version: '3'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana_server                             # 容器名为'kafka_server'
    # restart: always                                          # 指定容器退出后的重启策略为始终重启
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      ELASTICSEARCH_HOSTS: ${ELASTICSEARCH_HOSTS}          # http://elasticsearch_server:9200
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL}
      elasticsearch.ssl.verificationMode: none
      ELASTICSEARCH_USERNAME: ${KIBANA_USER}
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
      I18N_LOCALE: zh-CN
      SERVER_HOST: "0.0.0.0"
      SERVER_SHUTDOWNTIMEOUT: 5s
    ports:                              # 映射端口
      - "5601:5601"