version: '3'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    command:
    # MySQL8的密码验证方式默认是 caching_sha2_password，但是很多的连接工具还不支持该方式
    # 就需要手动设置下mysql的密码认证方式为以前的 mysql_native_password 方式
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    # docker的重启策略：在容器退出时总是重启容器，但是不考虑在Docker守护进程启动时就已经停止了的容器
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD} # root用户的密码
      # MYSQL_USER: user # 创建新用户 注意：此处需要容器启动后刷新权限，才可以使用详情请见当前目录下README.md
      # MYSQL_PASSWORD: 123456 # 新用户的密码
    ports:
      - 3306:3306
    volumes:
      - ${DATA_PATH}:/var/lib/mysql
      - ${CONF_PATH}:/etc/mysql/conf.d
      - ${LOGS_PATH}:/logs
      
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080