version: '3'
networks:
  kafka_net:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper                    # 原镜像`wurstmeister/zookeeper`
    container_name: zookeeper_server                 # 容器名为'zookeeper_server'
    restart: always                                  # 指定容器退出后的重启策略为始终重启
    volumes:                                         # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "/etc/localtime:/etc/localtime"
    ports:                                           # 映射端口
      - "2181:2181"
    networks:
      - kafka_net

  kafka:
    image: wurstmeister/kafka                                # 原镜像`wurstmeister/kafka`
    container_name: kafka_server                             # 容器名为'kafka_server'
    restart: always                                          # 指定容器退出后的重启策略为始终重启
    volumes:                                                 # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "/etc/localtime:/etc/localtime"
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      KAFKA_ADVERTISED_HOST_NAME: kafka_server  # TODO 本机IP
      KAFKA_ADVERTISED_PORT: 9092                      # 端口
      KAFKA_BROKER_ID: 0                # 在kafka集群中，每个kafka都有一个BROKER_ID来区分自己
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_server:9092 # TODO 将kafka的地址端口注册给zookeeper
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092        # 配置kafka的监听端口
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_server:2181 # TODO zookeeper地址
      KAFKA_CREATE_TOPICS: "hello_world"
      KAFKA_HEAP_OPTS : "-Xms64M -Xmx256M"
    ports:                              # 映射端口
      - "9092:9092"
    depends_on:                         # 解决容器依赖启动先后问题
      - zookeeper
    networks:
      - kafka_net

  kafka_manager:
    image: sheepkiller/kafka-manager                         # 原镜像`sheepkiller/kafka-manager`
    container_name: kafka_manager                            # 容器名为'kafka-manager'
    restart: always                                          # 指定容器退出后的重启策略为始终重启
    environment:                        # 设置环境变量,相当于docker run命令中的-e
      ZK_HOSTS: zookeeper_server:2181  # TODO zookeeper地址
      APPLICATION_SECRET:
      KAFKA_MANAGER_AUTH_ENABLED: "true"  # 开启kafka-manager权限校验
      KAFKA_MANAGER_USERNAME: admin       # 登陆账户
      KAFKA_MANAGER_PASSWORD: 123456      # 登陆密码
    ports:                              # 映射端口
      - "9001:9000"
    depends_on:                         # 解决容器依赖启动先后问题
      - kafka
    networks:
      - kafka_net
