version: '3'
services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-label
    volumes:
      - ${DATA_PATH}:/data
      - ${CONF_PATH}:/usr/local/etc/redis/redis.conf
      - ${LOGS_PATH}:/logs
    command: redis-server --requirepass ${REDIS_PASSWORD}
  #   #  两个写入操作 只是为了解决启动后警告 可以去掉
  #    /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
  #    && echo never > /sys/kernel/mm/transparent_hugepage/enabled
  #    && redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 6379:6379